In [1]:
import pandas as pd

In [2]:
swiss_prot_plants = pd.read_csv('data/swiss_prot_ec_plants.csv')

In [3]:
swiss_prot_plants

,accession,name,sequence,EC,lineage,species,taxonomy_id
0,Q7XQ85,1A12_ORYSJ,MAYQGIDLLSTKAAGDDHGENSSYFDGWKAYDTNPFDLRHNRGGVI...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
1,P18485,1A12_SOLLC,MGFEIAKTNSILSKLATNEEHGENSPYFDGWKAYDSDPFHPLKNPN...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Solanum lycopersicum,4081
2,A0A0P0WIY3,1A13_ORYSJ,MVGRMLSSPEPTLSTMAMSAAHGEDSPYFAGWRAYDEDPYDPITNP...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
3,Q42881,1A13_SOLLC,MKLLSEKATCNSHGQDSSYFLGWQEYEKNPYDEIQNPKGIIQMGLA...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Solanum lycopersicum,4081
4,Q43309,1A14_ARATH,MVQLSRKATCNSHGQVSSYFLGWEEYEKNPYDVTKNPQGIIQMGLA...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
...,...,...,...,...,...,...,...
15514,Q9FLM3,ZDH23_ARATH,MYVVTPPQRSGFGSDCDLRVYQTWKGSNIFCLQGRFIFGPDVRSLG...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15515,Q8VYS8,ZDH24_ARATH,MAGRVFEAWKGSNKFLFGGRLIFGPDAWSIPFTFLLIITPVCFFSV...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15516,Q9C533,ZDHC1_ARATH,MRKHGWQLPYHPLQVVAVAVFLALGFAFYVFFAPFVGKKIHQYIAM...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15517,Q3EC11,ZDHC2_ARATH,MDSSEIEVVPLDSNSHQSPTESPTITDVFSASAYGDLHQLKHFVEH...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15518,P56725,ZOX_PHAVU,MALNDETKVVVLLLPFPVQGHLNPFLQLSHLIAAQNIAVHYVGTVT...,2.4.2.40,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Phaseolus vulgaris,3885

In [4]:
# read in batches of 1000 with pandas
chunksize = 100000
accessions = []
for chunk in pd.read_csv("data/train_shuffled.csv", chunksize=chunksize):
    # chunk is a DataFrame. To "process" the rows in the chunk:
    accessions.extend(chunk['accession'].values)

/tmp/ipykernel_31807/1476891384.py:4: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("data/train_shuffled.csv", chunksize=chunksize):
/tmp/ipykernel_31807/1476891384.py:4: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("data/train_shuffled.csv", chunksize=chunksize):
/tmp/ipykernel_31807/1476891384.py:4: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("data/train_shuffled.csv", chunksize=chunksize):

In [5]:
swiss_prot_plants = swiss_prot_plants[~swiss_prot_plants['accession'].isin(accessions)]
swiss_prot_plants

,accession,name,sequence,EC,lineage,species,taxonomy_id
0,Q7XQ85,1A12_ORYSJ,MAYQGIDLLSTKAAGDDHGENSSYFDGWKAYDTNPFDLRHNRGGVI...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
1,P18485,1A12_SOLLC,MGFEIAKTNSILSKLATNEEHGENSPYFDGWKAYDSDPFHPLKNPN...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Solanum lycopersicum,4081
2,A0A0P0WIY3,1A13_ORYSJ,MVGRMLSSPEPTLSTMAMSAAHGEDSPYFAGWRAYDEDPYDPITNP...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
4,Q43309,1A14_ARATH,MVQLSRKATCNSHGQVSSYFLGWEEYEKNPYDVTKNPQGIIQMGLA...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
5,Q5W6F9,1A14_ORYSJ,MGVKLLADGCAGASSSPALSRVATSAAHGEGSPYFAGWKAYDEDPY...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
...,...,...,...,...,...,...,...
15514,Q9FLM3,ZDH23_ARATH,MYVVTPPQRSGFGSDCDLRVYQTWKGSNIFCLQGRFIFGPDVRSLG...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15515,Q8VYS8,ZDH24_ARATH,MAGRVFEAWKGSNKFLFGGRLIFGPDAWSIPFTFLLIITPVCFFSV...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15516,Q9C533,ZDHC1_ARATH,MRKHGWQLPYHPLQVVAVAVFLALGFAFYVFFAPFVGKKIHQYIAM...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15517,Q3EC11,ZDHC2_ARATH,MDSSEIEVVPLDSNSHQSPTESPTITDVFSASAYGDLHQLKHFVEH...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15518,P56725,ZOX_PHAVU,MALNDETKVVVLLLPFPVQGHLNPFLQLSHLIAAQNIAVHYVGTVT...,2.4.2.40,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Phaseolus vulgaris,3885

In [6]:
validation = pd.read_csv("data/validation.csv")

/tmp/ipykernel_31807/485496488.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  validation = pd.read_csv("data/validation.csv")

In [7]:
swiss_prot_plants = swiss_prot_plants[~swiss_prot_plants['accession'].isin(validation['accession'].values)]
swiss_prot_plants

,accession,name,sequence,EC,lineage,species,taxonomy_id
0,Q7XQ85,1A12_ORYSJ,MAYQGIDLLSTKAAGDDHGENSSYFDGWKAYDTNPFDLRHNRGGVI...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
2,A0A0P0WIY3,1A13_ORYSJ,MVGRMLSSPEPTLSTMAMSAAHGEDSPYFAGWRAYDEDPYDPITNP...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
4,Q43309,1A14_ARATH,MVQLSRKATCNSHGQVSSYFLGWEEYEKNPYDVTKNPQGIIQMGLA...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
6,P29535,1A14_SOLLC,MDLETSEISNYKSSVVLSKLASNEQHGENSPYFDGWKAYDNDPFHL...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Solanum lycopersicum,4081
8,A0A0P0UZP7,1A15_ORYSJ,MIMSGFHIGIYTSICLYIPLPHLEPWIISSHTPKNLNLLDCLLYCS...,4.4.1.14,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. japonica,39947
...,...,...,...,...,...,...,...
15504,O64778,Y1142_ARATH,MGKKWIVFFAYLLLSSFFISSSSAGITKESPLPIGQTLSSSNGFYE...,2.7.11.1,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15512,Q8L733,Y4121_ARATH,MFRFNFRREISKYTGIYHRKIHSGLEDAGPMASRLKSRSVVRFSGP...,2.1.-.-,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15514,Q9FLM3,ZDH23_ARATH,MYVVTPPQRSGFGSDCDLRVYQTWKGSNIFCLQGRFIFGPDVRSLG...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15517,Q3EC11,ZDHC2_ARATH,MDSSEIEVVPLDSNSHQSPTESPTITDVFSASAYGDLHQLKHFVEH...,2.3.1.225,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Arabidopsis thaliana,3702
15518,P56725,ZOX_PHAVU,MALNDETKVVVLLLPFPVQGHLNPFLQLSHLIAAQNIAVHYVGTVT...,2.4.2.40,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Phaseolus vulgaris,3885

In [8]:
import re

def get_ec_from_regex_match(match):
    if match is not None:
        EC = match.group()
        if EC is not None:
            return EC
    return None

def get_ecs_from_string(EC):
    EC3 = []
    EC2 = []
    EC1 = []
    EC4 = []
    new_EC = re.search(r"^\d+.\d+.\d+.n*\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC4:
            EC4.append(new_EC)

    new_EC = re.search(r"^\d+.\d+.\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC3:
            EC3.append(new_EC)

    new_EC = re.search(r"^\d+.\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC2:
            EC2.append(new_EC)

    new_EC = re.search(r"^\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC1:
            EC1.append(new_EC)
    return EC1, EC2, EC3, EC4

In [9]:
validation.iloc[:, 8:]
# create new columns for each EC in the swiss_prot_plants dataset
for EC in validation.iloc[:, 8:]:
    
    swiss_prot_plants[EC] = 0

/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swiss_prot_plants[EC] = 0
/tmp/ipykernel_31807/1661798862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [10]:
columns = swiss_prot_plants.columns
for i, row in swiss_prot_plants.iterrows():
    EC1, EC2, EC3, EC4 = get_ecs_from_string(row['EC'])
    for EC in EC1:
        if EC in columns:
            swiss_prot_plants.at[i, EC] = 1
    for EC in EC2:
        if EC in columns:
            swiss_prot_plants.at[i, EC] = 1
    for EC in EC3:
        if EC in columns:
            swiss_prot_plants.at[i, EC] = 1
    for EC in EC4:
        if EC in columns:
            swiss_prot_plants.at[i, EC] = 1

In [16]:
swiss_prot_plants.to_csv('swiss_prot_ec_plants.csv', index=False)

In [4]:
ecs_plants = set(swiss_prot_plants['EC'])

In [5]:
test_ = pd.read_csv('data/test.csv')

/tmp/ipykernel_25317/2300665504.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  test_ = pd.read_csv('data/test.csv')

In [ ]:
test_[test_]

In [6]:
ecs = set(test_.columns[8:])
ecs

{'7.4.2.8',
 '5.4.2.7',
 '2.7.1.55',
 '3.4.11.23',
 '6.5.1.3',
 '7.2.2.8',
 '1.8.98',
 '3.2.1.132',
 '1.3.1.25',
 '5.3.1.25',
 '3.6.4',
 '2.7.4.1',
 '2.7.1.33',
 '2.9.1.2',
 '1.13.11.11',
 '3.5.1.91',
 '2.1.2.10',
 '3.7.1.12',
 '2.3.1.189',
 '3.1.6.12',
 '6.3.3.3',
 '3.4.16.6',
 '2.3.2.8',
 '2.4.1.15',
 '4.3.1.12',
 '1.14.99.46',
 '3.4.24.39',
 '1.17.5.2',
 '1.3.5',
 '2.7.13',
 '1.4.3.5',
 '3.2.2.24',
 '3.3.2.10',
 '4.3.2.1',
 '3.1.3',
 '1.97',
 '2.7.2.7',
 '1.1.2.3',
 '1.14.11.20',
 '1.1.1.336',
 '5.1.3.4',
 '2.7.3.3',
 '1.1.1.25',
 '2.1.1.17',
 '3.1.21.2',
 '2.4.99.21',
 '2.7.7.18',
 '4.1.1.112',
 '3.6.1.40',
 '3.6.1.31',
 '1.14.12.10',
 '4.2.1.108',
 '3.1.4',
 '2.1.1.314',
 '3.5.99.2',
 '2.6.1.17',
 '2.8.3',
 '2.4.1.244',
 '3.11',
 '1.5.1.38',
 '3.7.1.20',
 '1.14.15.24',
 '1.14.13.114',
 '2.7.2.17',
 '6.3.5.13',
 '2.4.1.21',
 '2.5.1.1',
 '4.1.1.15',
 '2.2.1.9',
 '5.1.3.21',
 '1.4.1.16',
 '1.8.99.2',
 '3.5.5.1',
 '2.3.1.19',
 '1.4.99.5',
 '1.6.5.2',
 '2.5.1.73',
 '4.1.99.14',
 '2.1.1.166',
 '1.1.1.169',
 '1.2.1.27',
 '2.4.1.280',
 '3.4.23.21',
 '4.2.1.8',
 '4.1.1.111',
 '3.7',
 '3.1.1.7',
 '1.2.1.26',
 '3.4.24.78',
 '3.1.21.1',
 '1.2.5.3',
 '2.4.1.122',
 '2.7.7.68',
 '3.2.1.41',
 '2.8.4.4',
 '1.14.19.18',
 '2.7.7.84',
 '3.4.13.19',
 '1.3.8.3',
 '1.8.1.7',
 '4.1.2.48',
 '1.14.12.7',
 '7.2.2.6',
 '3.1.4.3',
 '2.1.1.359',
 '1.1.1.30',
 '2.4.1.211',
 '3.2.1.158',
 '1.17.4.1',
 '1.8.4.12',
 '1.1.1.136',
 '3.2.2.22',
 '5.4.99.61',
 '6.1.1.9',
 '2.7.11.11',
 '3.5.1.28',
 '4.1.1.75',
 '1.11.1.8',
 '6.2.1.20',
 '3.1.21.4',
 '6.3.2.13',
 '2.7.7.70',
 '4.1.99.22',
 '3.1.31',
 '1.1.3.15',
 '1.1.1.385',
 '1.3.1.95',
 '1.7.2.3',
 '4.2.1.126',
 '2.5.1.25',
 '2.7.6.2',
 '2.7.2.8',
 '3.1.3.15',
 '2.5.1.140',
 '5.3.1.17',
 '1.14.19.3',
 '6.2.1.45',
 '3.5.1.11',
 '1.5.1.50',
 '2.3.1.199',
 '4.99.1.3',
 '2.7.1.92',
 '3.5.4.1',
 '2.3.1.266',
 '5.4.2.2',
 '2.7.7.56',
 '1.1.1.290',
 '2.4.1.287',
 '3.5.99.6',
 '4.2.1.33',
 '1.1.98.2',
 '1.6.3',
 '1.10.3.1',
 '1.14.13.81',
 '2.4.1.58',
 '7.6.2.2',
 '2.7.7.105',
 '7.2.1.1',
 '5.4.99.9',
 '6.3.4.5',
 '7.4.2',
 '1.5.8',
 '2.7.1.184',
 '1.2.1.5',
 '2.5.1.76',
 '3.4.17',
 '7.1.1.6',
 '6.2.1.22',
 '3.1.3.11',
 '3.2.2.26',
 '2.1.1.74',
 '3.4.19.12',
 '2.2.1.10',
 '3.5.3.6',
 '4.1.1.2',
 '1.8.1',
 '5.4.99.60',
 '6.2.1.30',
 '3.1.1.117',
 '2.3.1.1',
 '1.1.1.21',
 '5.1.1.10',
 '2.4.1.25',
 '6.2.1.54',
 '2.7.11.23',
 '1.3.1.93',
 '2.5.1.6',
 '3.1.13',
 '2.3.1.169',
 '3.2.1.106',
 '2.3.3.14',
 '2.5.1.97',
 '2.7.4.7',
 '3.5.1.52',
 '3.1.1.4',
 '4.1.1.18',
 '3.5.4.10',
 '2.10',
 '1.12.7',
 '3.1.4.14',
 '4.1.2.49',
 '1.21.4.1',
 '2.1.1.206',
 '4.1.1.79',
 '2.1.1.10',
 '1.1.1.130',
 '2.7.1.183',
 '2.7.7.101',
 '2.5.1.42',
 '5.4.2.12',
 '3.1.3.41',
 '4.2.1.9',
 '2.3.1.86',
 '5.1.1.13',
 '2.3.1',
 '3.5.1.56',
 '1.14.11.55',
 '4.2.1.7',
 '1.1.1.4',
 '2.3.1.129',
 '2.1.1.179',
 '3.13.2',
 '6.3.1.2',
 '3.5.1.14',
 '4.1.1.85',
 '1.1.1.34',
 '1.3.1.89',
 '7.2.2',
 '1.2.5.1',
 '2.4.1.152',
 '3.6.1.57',
 '4.6.1.19',
 '3.5.3.8',
 '3.4.24.84',
 '3.1.6.14',
 '4.2.1.28',
 '2.4.2.29',
 '2.3.3.21',
 '3.6.1.62',
 '4.2.2.23',
 '2.7.7.41',
 '2.7.7.75',
 '4.3.3.5',
 '3.4.14.11',
 '1.5.1.7',
 '2.8.1.13',
 '2.4.1.4',
 '1.2.1.103',
 '4.1.1.23',
 '3.1.4.38',
 '1.1.1.69',
 '4.2.1.82',
 '4.2.1.2',
 '5.3.1.28',
 '3.6.1.1',
 '6.3.5.7',
 '3.1.2.30',
 '3.1.21.10',
 '1.3.1.86',
 '1.1.1.298',
 '3.1.26.5',
 '2.7.1.90',
 '3.5.1.130',
 '1.1.1.153',
 '2.1.1.271',
 '3.4.22.44',
 '1.1.1.368',
 '2.6.1.21',
 '3.6.5.3',
 '4.1.1.25',
 '1.14.99.29',
 '5.4.3',
 '3.1.3.8',
 '2.7.11.21',
 '1.17.4',
 '1.17.99',
 '7.5.2',
 '4.3.99',
 '4.2.1.132',
 '2.7.1.172',
 '3.1.4.4',
 '3.1.1.72',
 '1.13.11.53',
 '3.1.3.68',
 '4.2.1.119',
 '1.17.7',
 '2.6.99',
 '4.6.1',
 '1.2.7.12',
 '4.1.1.8',
 '4.2.1.96',
 '3.4.14.1',
 '6.2.1.13',
 '2.4.2.53',
 '6.1.1.6',
 '2.6.1.90',
 '2.1.1.211',
 '2.7.1.11',
 '2.4.99.18',
 '2',
 '4.1.1.49',
 '1.8.4.2',
 '1.8.7.1',
 '5.1.3.22',
 '2.1.3.3',
 '2.6.1.9',
 '2.1.2.7',
 '3.3',
 '3.5.1.2',
 '1.5.1.28',
 '3.1.1.2',
 '1.17.1.4',
 '1.12.1.2',
 '1.14.99.39',
 '3.2.1.39',
 '1.1.1.122',
 '3.5.1.77',
 '6.4.1',
 '5.2.1.4',
 '2.1.1.86',
 '5.1.1.23',
 '3.2.1.18',
 '4.2.1.134',
 '3.2',
 '1.1.1.1',
 '3.6.1.17',
 '1.21.4.2',
 '2.3.1.81',
 '3.5.2.2',
 '2.1.1.44',
 '4.2.1.18',
 '1.1.1.271',
 '5.1.1.7',
 '3.4.24.13',
 '1.4.99',
 '1.8.1.15',
 '3.1.3.104',
 '3.4.11.4',
 '2.5.1.32',
 '3.5.4.40',
 '3.2.1.85',
 '5.3.1.30',
 '3.1.1.89',
 '1.1.1.17',
 '3.7.1.3',
 '7.3.2.7',
 '2.7.1.158',
 '3.1.3.45',
 '2.1.1.298',
 '6.3.1.19',
 '2.3.1.251',
 '3.5.1.96',
 '3.2.1.180',
 '3.6.1.66',
 '1.5.1.5',
 '6.4.1.7',
 '1.14.15.29',
 '2.4.1.183',
 '3.1.11.6',
 '1.14.99.1',
 '6.1.1.7',
 '3.1.8',
 '5.3',
 '3.4.24.56',
 '5.3.3.4',
 '1.4.3.10',
 '3.6.1.74',
 '1.2.1.24',
 '3.1.12.1',
 '1.1.1.251',
 '1.9.6',
 '1.5.5.2',
 '2.1.1.321',
 '2.7.1.19',
 '5.1.1.3',
 '2.5.1.94',
 '3.2.1.177',
 '3.4.24.85',
 '3.4.23.12',
 '5.4.2.10',
 '2.4.2.52',
 '1.14.16',
 '2.5.1',
 '2.4.1.221',
 '3.5.3.1',
 '5.3.1.8',
 '1.5.1.3',
 '1.1.1.88',
 '2.7.7.60',
 '1.1.1.262',
 '3.1.6.6',
 '2.1.2.1',
 '5.4.99.27',
 '1.2.4.1',
 '6.3.2.45',
 '1.1.1.26',
 '5.3.1.22',
 '2.7.1.67',
 '5',
 '3.13.1.9',
 '1.14.18',
 '6.1.1.3',
 '1.8.1.16',
 '1.17.4.4',
 '4.2.1.90',
 '1.14.13.7',
 '6.4.1.1',
 '1.1.1.18',
 '1.1.99.1',
 '2.3.2.16',
 '1.14.13.25',
 '2.8.4.3',
 '2.7.7.52',
 '2.7.8.6',
 '4.2.1.39',
 '5.5.1.4',
 '2.7.7.24',
 '1.1.1.163',
 '3.7.1.2',
 '1.3.1.70',
 '2.1.1.170',
 '2.4.1.187',
 '1.6.5.4',
 '1.7.1.17',
 '3.4.21.73',
 '1.8.3.4',
 '1.1.1.306',
 '4.3.2.8',
 '1.3.1.12',
 '2.3.1.157',
 '2.4.1.13',
 '2.7.9.3',
 '4.3.3.7',
 '5.1.99.6',
 '6.6',
 '1.11.1.6',
 '1.3.99.31',
 '1.1.1.133',
 '1.7.1.3',
 '1.13.12.3',
 '3.5.3.12',
 '3.4.23.34',
 '1.1.1.49',
 '1.14.13.59',
 '1.14.13.196',
 '2.7.7.61',
 '1.17.1',
 '1.1.1.140',
 '3.5.3.18',
 '1.5.99.14',
 '3.1.1.32',
 '1.3.3.3',
 '2.1.1.107',
 '3.4.19',
 '2.1.1.33',
 '3.1.1.22',
 '5.4.99.24',
 '1.17.1.9',
 '2.4.2.45',
 '1.1.99.24',
 '2.7.1.150',
 '2.7.7.81',
 '3.13.1.1',
 '5.5.1',
 '1.17',
 '5.4.2.9',
 '1.2.7.3',
 '3.2.1.99',
 '5.1.2.7',
 '1.3.99.33',
 '3.1.12',
 '1.3.1.76',
 '3.4.21.47',
 '6.2.1.12',
 '2.3.1.225',
 '3.5.4.4',
 '3.4.21.7',
 '1.14.16.4',
 '2.9.1.3',
 '1.14.15.32',
 '1.1.1.371',
 '3.4.21.110',
 '3.4.21.63',
 '2.3.1.176',
 '1.2.1.71',
 '2.1.1.181',
 '4.99.1',
 '2.4.1.241',
 '1.1.1.60',
 '2.7.12.1',
 '3.6.1.25',
 '4.2.1.83',
 '1.4.3.3',
 '2.7.7.71',
 '2.1.1.98',
 '3.7.1.22',
 '3.9',
 '4.1.3.3',
 '1.1.2.7',
 '2.4.1.131',
 '3.3.2.9',
 '1.7.5',
 '1.14.11.27',
 '2.7.7.82',
 '3.4.16.4',
 '1.1.1.244',
 '3.4.15.6',
 '2.6.1.45',
 '2.6.1.59',
 '2.1.1.225',
 '6.1.1.17',
 '1.1.3.9',
 '1.3.1.34',
 '2.3.1.183',
 '4.1.2.20',
 '3.6.1',
 '3.6.5',
 '1.1.1.3',
 '2.7.1.20',
 '3.1.1.96',
 '4.1.1.47',
 '1.1.5.12',
 '2.6.1.11',
 '3.5.2.9',
 '1.3.99.5',
 '2.7.1.85',
 '4.98',
 '3.4.19.13',
 '4.98.1',
 '1.8',
 '2.7.1.108',
 '2.7.8.28',
 '2.7.7.33',
 '5.1.3.23',
 '1.14.13.149',
 '1.20.4.1',
 '2.7.1.71',
 '2.7.7.59',
 '3.4.21.93',
 '4.1.1.44',
 '1.2.1.88',
 '1.1.1.308',
 '1.14.13.92',
 '2.7',
 '1.1.99.31',
 '1.16.1.1',
 '2.1.1.137',
 '1.7.3.3',
 '1.13.11.57',
 '1.8.2',
 '2.7.7.39',
 '3.1.1.57',
 '3.4.19.11',
 '2.3.1.97',
 '1.3.1.28',
 '4.4.1.14',
 '2.6.1.62',
 '1.5.3',
 '2.3.1.243',
 '1.11.1.9',
 '2.7.1.83',
 '2.3.2',
 '2.7.7.23',
 '6.4.1.3',
 '5.4.99.28',
 '1.14.14.46',
 '2.1.1.264',
 '4.2.1.40',
 '3.8.1.2',
 '1.1.99',
 '1.18.1.3',
 '3.6.5.5',
 '4.2.1.41',
 '2.1.1.156',
 '2.5.1.62',
 '3.5.1.16',
 '2.1.1.61',
 '1.14.11.4',
 '3.2.2.6',
 '3.5.99.7',
 '7.6.2',
 '6.3.1.1',
 '1.13.11.4',
 '2.3.1.28',
 '1.12.2.1',
 '2.4.2.17',
 '2.1.1.56',
 '3.1.4.1',
 '2.3.2.3',
 '4.1.1.19',
 '4.4.1.22',
 '4.1.1.39',
 '5.3.99.11',
 '7.2.2.14',
 '4.6.1.13',
 '4.1.1.22',
 '2.1.1.216',
 '3.5.1.10',
 '3.4.13.23',
 '2.1.1.198',
 '1.4.1.21',
 '4.3.99.4',
 '1.1.1.83',
 '7.3',
 '1.4',
 '6.3.1.8',
 '6.3.2.3',
 '4.7.1.1',
 '2.4.2.48',
 '2.7.11.10',
 '2.7.3.2',
 '1.1.1.343',
 '2.7.1.56',
 '7.1.1.8',
 '3.1.4.37',
 '3.4.21.72',
 '2.4.1.54',
 '2.7.11.7',
 '3.4.22.54',
 '1.1.1.274',
 '3.5.5.7',
 '3.5.1.59',
 '5.6.2.2',
 '2.4.1.14',
 '4',
 '3.4.11.6',
 '1.18.1.1',
 '3.4.21.50',
 '2.1.2.11',
 '1.14.11.9',
 '3.5.1.15',
 '3.5.3.7',
 '5.2.1.13',
 '1.14.13.20',
 '2.1.1.100',
 '2.2.1.7',
 '1.13.12.4',
 '3.7.1.17',
 '2.1.1.355',
 '1.4.3.13',
 '4.1.3.38',
 '2.7.1.16',
 '4.1.99.19',
 '2.7.7.14',
 '2.3.1.85',
 '2.1.1.85',
 '6.2.1.1',
 '2.3.2.26',
 '1.2.7.1',
 '2.1.1.132',
 '2.5.1.90',
 '1.8.99',
 '1.1.1.157',
 '1.1.1.405',
 '1.1.1.320',
 '3.6.1.65',
 '4.1.1.1',
 '3.2.1.3',
 '1.14.12.19',
 '6.1.1.22',
 '1.1.1.94',
 '3.1.4.35',
 '1.3.8.6',
 '3.5.3.13',
 '4.2.1.1',
 '4.1.3.34',
 '3.3.2.8',
 '3.6.1.23',
 '1.8.1.4',
 '2.7.7.79',
 '2.1',
 '2.1.1.297',
 '1.16.3.1',
 '1.15.1.1',
 '5.4.3.9',
 '1.1.1.103',
 '3.4.21.62',
 '2.1.1.354',
 '4.1.1.90',
 '3.2.1.1',
 '3.5.1',
 '1.2.3',
 '2.3.1.255',
 '2.9',
 '4.2.1.116',
 '4.2.1.12',
 '2.4.2.14',
 '2.4.1.135',
 '4.2.1.25',
 '1.14.14.18',
 '3.5.1.135',
 '3.6.1.12',
 '4.2.1.115',
 '1.7.1.7',
 '1.8.3.2',
 '2.3.1.102',
 '2.7.7.8',
 '3.1',
 '3.2.1.6',
 '3.5.1.13',
 '1.8.2.3',
 '4.3.2.3',
 '3.1.1.47',
 '3.4.19.9',
 '5.3.3.8',
 '3.1.7',
 '2.1.1.174',
 '2.3.3.10',
 '3.4.21.92',
 '6.1.1.1',
 '2.3.1.48',
 '2.3.1.20',
 '2.4.1.258',
 '2.5',
 '1.1.1.218',
 '2.4.1.284',
 '3.2.1.165',
 '3.4.25.1',
 '6.3.2.17',
 '3.1.31.1',
 '3.4.13.21',
 '3.4.21.108',
 '3.1.1.41',
 '1.4.4',
 '2.7.11.26',
 '1.2.1.84',
 '5.3.2',
 '2.1.1.187',
 '2.3.1.61',
 '4.1.3.43',
 '1.12.1.3',
 '1.1.1.346',
 '2.4.99.12',
 '2.3.1.109',
 '2.7.4.22',
 '2.7.3',
 '2.6.1.98',
 '2.7.8.11',
 '2.6.1.48',
 '6.3.4.18',
 '2.4.1.101',
 '5.4.99.2',
 '1.17.4.2',
 '1.14.11.67',
 '2.7.12.2',
 '6.1.1.19',
 '6.3.4.6',
 '1.1.1.56',
 '1.13.11',
 '2.7.4.8',
 '4.1.1.28',
 '5.1.3.17',
 '4.1.1.96',
 '3.4.17.21',
 '6.1.1.23',
 '5.1.3.2',
 '6.3.4.22',
 '1.13.11.6',
 '2.8.3.22',
 '4.2.1',
 '3.2.1.93',
 '3.4.22.15',
 '3.1.1.45',
 '1.5.5',
 '1.14.14.12',
 '1.6.2.2',
 '3.2.1.143',
 '2.1.1.71',
 '3.2.1.67',
 '3.4.24.3',
 '6.3.2.5',
 '3.4.21.116',
 '3.1.6.1',
 '1.13.99',
 '6.3.1.12',
 '3.2.1.131',
 '2.1.1.266',
 '3.4.23',
 '3.1.11.2',
 '2.1.1.250',
 '3.5.1.29',
 '1.3.5.6',
 '4.2.2.2',
 '6.4',
 '1.4.4.2',
 '2.3.1.37',
 '2.7.8.40',
 '2.8.1.12',
 '3.5.1.82',
 '5.3.3.6',
 '3.1.1.61',
 '2.3.1.184',
 '1.2.1.59',
 '3.4.24.81',
 '2.1.1.282',
 '5.1.3.10',
 '2.3.1.4',
 '2.4.1.230',
 '2.7.4.3',
 '2.3.1.179',
 '2.7.2',
 '1.3.98.1',
 '2.4.2.41',
 '2.5.1.39',
 '3.4.22.71',
 '2.3.1.74',
 '2.4.2.9',
 '3.1.3.77',
 '2.3.1.50',
 '2.1.1.208',
 '2.5.1.103',
 '5.5.1.19',
 '3.5.4.19',
 '3.1.1.17',
 '2.7.4.27',
 '1.3.1.54',
 '3.1.4.55',
 '3.2.1.50',
 '3.4.21.68',
 '2.1.1.57',
 '1.1.1.370',
 '2.7.7.49',
 '3.2.1.70',
 '4.3.1.32',
 '3.11.1.2',
 '3.1.26.8',
 '2.1.1.178',
 '4.3.1.1',
 '3.5.99',
 '2.7.8.23',
 '1.4.3.16',
 '2.3.1.57',
 '4.1.1.4',
 '1.3.5.2',
 '1.13.11.27',
 '3.1.3.7',
 '1.4.1',
 '3.5.1.122',
 '4.2.1.51',
 '3.3.2',
 '5.1.99.5',
 '3.5.4.36',
 '6.3.3',
 '1.1.9.1',
 '2.4.1.217',
 '3.1.3.73',
 '5.3.1.23',
 '2.4.1.290',
 '3.7.1',
 '2.1.1.356',
 '2.4.2.30',
 '1.1.1.317',
 '2.7.7',
 '3.2.1.51',
 '1.14.14.3',
 '2.7.1.23',
 '4.4.1.15',
 '2.7.11.18',
 '3.5.5.8',
 '1.2.1.32',
 '1.14.15',
 '1.5.3.6',
 '1.3.1.33',
 '1.1.1.203',
 '3.4.22.49',
 '5.4.4.2',
 '2.1.3',
 '2.4.2.2',
 '2.7.1.60',
 '3.5.1.1',
 '3.1.3.27',
 '1.2.7.11',
 '3.2.1',
 '4.3.1.2',
 '6.1.1',
 '3.1.4.50',
 '3.1.11.5',
 '6.3.5.3',
 '3.5.1.104',
 '3.4.11',
 '2.6.1.88',
 '2.1.2.5',
 '2.4.2.7',
 '2.4.1.109',
 '2.6.1.36',
 '2.8.1.9',
 '1.14.19',
 '2.7.4.16',
 '3.5.3.11',
 '1.4.1.11',
 '3.5.1.84',
 '1.8.1.8',
 '6.1.1.4',
 '1.2.7.5',
 '3.1.26.11',
 '3.1.3.74',
 '3.4.14.5',
 '4.1.3.40',
 '1.3.1.75',
 '2.4.1.267',
 '1.18.1',
 '1.11.1.10',
 '4.3.2.2',
 '6.3.4.23',
 '5.3.1.9',
 '4.1.99.17',
 '4.1.3.27',
 '2.2.1.6',
 '3.2.1.49',
 '1.3.99.4',
 '3.5.1.32',
 '1.11.1',
 '4.3.1',
 '5.4.99.12',
 '1.2.3.1',
 '2.1.1.361',
 '1.4.1.23',
 '4.2.1.3',
 '3.5.2',
 '3.5.4.16',
 '3.1.2',
 '7.1.2',
 '2.7.4.6',
 '1.2.1.76',
 '2.1.1.5',
 '3.8.1',
 '3.1.3.67',
 '3.4.21.109',
 '3.5.2.1',
 '1.3.1.106',
 '1',
 '3.1.4.53',
 '3.5.1.87',
 '5.1.3.15',
 '2.1.1',
 '1.16.1.9',
 '4.99',
 '7.4',
 '1.1.1.269',
 '2.7.1.144',
 '2.1.1.35',
 '1.1.1.58',
 '2.7.11.22',
 '2.1.1.203',
 '5.99.1',
 '4.2.1.150',
 '6.3.3.1',
 '2.3.1.191',
 '4.1.2.17',
 '2.1.3.12',
 '3.5.4.28',
 '2.4.1.289',
 '4.1',
 '4.2.1.109',
 '3.1.2.22',
 '4.3.2.9',
 '1.1.1.42',
 '3.2.1.8',
 '2.6.1.13',
 '3.4.25',
 '3.5.1.47',
 '2.7.7.106',
 '2.3.1.269',
 '3.5',
 '1.12.98',
 '2.7.1.36',
 '2.3.1.275',
 '3.2.1.54',
 '3.5.1.118',
 '4.1.1.31',
 '2.4.2.8',
 '3.6.1.73',
 '1.8.4.8',
 '4.1.1.5',
 '2.4.2.10',
 '4.2.1.75',
 '3.4.24.71',
 '1.1.1.8',
 '2.7.1.1',
 '1.14.13.9',
 '1.5.8.3',
 '2.7.11.24',
 '2.7.7.6',
 '3.5.2.12',
 '1.14.14.5',
 '2.3.3.16',
 '5.1.3.25',
 '4.1.1.81',
 '2.7.13.3',
 '1.5.99.12',
 '3.6.1.41',
 '2.7.7.73',
 '2.5.1.30',
 '4.2.3.13',
 '2.7.1.165',
 '2.8.2',
 '3.5.4.44',
 '3.1.3.48',
 '5.6.1.6',
 '6.3.2',
 ...}

In [10]:
del test_

In [7]:
import re

def get_ec_from_regex_match(match):
    if match is not None:
        EC = match.group()
        if EC is not None:
            return EC
    return None
    

EC3 = []
EC2 = []
EC1 = []
EC4 = []
for EC in ecs_plants:
    new_EC = re.search(r"^\d+.\d+.\d+.n*\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC4:
            EC4.append(new_EC)

    new_EC = re.search(r"^\d+.\d+.\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC3:
            EC3.append(new_EC)

    new_EC = re.search(r"^\d+.\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC2:
            EC2.append(new_EC)

    new_EC = re.search(r"^\d+", EC)
    new_EC = get_ec_from_regex_match(new_EC)
    if isinstance(new_EC, str):
        if new_EC not in EC1:
            EC1.append(new_EC)

In [14]:
"5.5.1" in set(EC)

True

In [9]:
EC = EC1 + EC2 + EC3 + EC4

In [17]:
"5.5.1" in (set(EC) & ecs)

True

In [ ]:
len(EC1 & ecs)

In [14]:
len(ecs_plants) - len(ecs_plants - ecs)

2771