In [8]:
import pandas as pd
secondary_metabolites = pd.read_html("https://www.genome.jp/kegg/tables/br08011.html", header=0)

In [9]:
secondary_metabolites[0]

,Map,Pathway,Module,KEGG ID,Name,Remark
0,00902,Geraniol biosynthesis,NaN,C01500,Geraniol,Monoterpenoid
1,00902,Myrcene biosynthesis,NaN,C06074,Myrcene,Monoterpenoid
2,00902,Limonene biosynthesis,NaN,C00521 C06099,(S)-Limonene (R)-Limonene,Monoterpenoid
3,00902,Menthol biosynthesis,NaN,C00400,Menthol,Monoterpenoid
4,00902,Carvone biosynthesis,NaN,C01767 C11383,(-)-Carvone (+)-Carvone,Monoterpenoid
...,...,...,...,...,...,...
148,00997,Aerobactin biosynthesis,M00918,C05554,Aerobactin,Siderophore
149,00997,Cyclooctatin biosynthesis,M00921,C21979,Cyclooctatin,"Diterpenoid, lysophospholipase inhibitor"
150,00997,Lovastatin biosynthesis,M00893,C21130,Lovastatin acid,Fungal polyketide
151,00997,Grixazone biosynthesis,M00905,C20799,Grixazone B,"Grixazone, yellow pigment"
152,00997,Ethynylserine biosynthesis,M00906,C22141,L-β-Ethynylserine,Non-proteinogenic amino acid

In [10]:
import io
from Bio.KEGG import REST as kegg_api


def get_ec_in_pathway(pathway):
    res = []
    try:
        result = kegg_api.kegg_link("enzyme", f"path:{pathway}").read()
        try:
            result_enzymes = pd.read_table(io.StringIO(result), header=None)
            for enzyme in result_enzymes.iloc[:, 1]:
                res.append(enzyme.replace("ec:", ""))

        except:
            pass
    except:
        print(f"{pathway}")
        return res

    return res

In [11]:
maps = secondary_metabolites[0].loc[:, ["Map", "Remark"]]
maps

       Map                                    Remark
0    00902                             Monoterpenoid
1    00902                             Monoterpenoid
2    00902                             Monoterpenoid
3    00902                             Monoterpenoid
4    00902                             Monoterpenoid
..     ...                                       ...
148  00997                               Siderophore
149  00997  Diterpenoid, lysophospholipase inhibitor
150  00997                         Fungal polyketide
151  00997                 Grixazone, yellow pigment
152  00997              Non-proteinogenic amino acid

[153 rows x 2 columns]

In [12]:
maps_enzymes = {}
for i in range(len(maps)):
    map_ = maps.iloc[i, 0]
    description = maps.iloc[i, 1]

    maps_ = map_.split(" ")
    for map_ in maps_:
        map_clean = f"map{map_}"
        if map_clean not in maps_enzymes:
            maps_enzymes[map_clean] = get_ec_in_pathway(map_clean)

map01057

In [20]:
maps_enzymes["map00253"] = get_ec_in_pathway("map00253")

In [13]:
len(maps_enzymes)

43

In [28]:
import json

with open("secondary_metabolism_enzymes_plantcyc.json", "r") as f:
    maps_enzymes_plant_cyc = json.load(f)

In [29]:
sm_ec_numbers = []
for ec in maps_enzymes_plant_cyc.values():
    sm_ec_numbers.extend(ec)

In [30]:
sm_ec_numbers = list(set(sm_ec_numbers))

In [31]:
len(sm_ec_numbers)

419

In [17]:
for ec in maps_enzymes_plant_cyc.values():
    sm_ec_numbers.extend(ec)

In [32]:
len(sm_ec_numbers)

419

In [33]:
import pandas as pd

ec_plants = pd.read_csv("data/swiss_prot_ec_plants.csv")
ids_sm = []
for i, ec_numbers in enumerate(ec_plants.EC):
    ec = ec_numbers.split(";")
    for ec_ in ec:
        if ec_ in sm_ec_numbers:
            ids_sm.append(i)
            break

In [34]:
ids_sm

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 21,
 22,
 23,
 51,
 59,
 60,
 61,
 156,
 158,
 159,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 184,
 189,
 210,
 224,
 225,
 237,
 239,
 240,
 241,
 268,
 270,
 271,
 300,
 301,
 323,
 324,
 325,
 326,
 327,
 363,
 398,
 399,
 400,
 401,
 421,
 422,
 423,
 444,
 445,
 446,
 447,
 483,
 484,
 485,
 518,
 555,
 560,
 561,
 568,
 569,
 572,
 579,
 582,
 585,
 592,
 593,
 622,
 623,
 624,
 625,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 648,
 662,
 663,
 665,
 666,
 667,
 668,
 669,
 670,
 674,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 748,
 831,
 832,
 834,
 836,
 837,
 1013,
 1262,
 1263,
 1285,
 1311,
 1312,
 1313,
 1352,
 1361,
 1377,
 1378,
 1379,
 1381,
 1382,
 1383,
 1385,
 1386,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1448,
 1449,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1471,
 1473,
 1474,
 1475,
 1477,
 1478,
 1479,
 1481,
 1484,
 1514,
 1515,
 1653,
 1657,
 1658,
 1659,
 1660,
 1661,
 1662,
 1663,
 1664,
 1665,
 1666,
 1667,
 1668,
 1701,
 1707,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1789,
 1790,
 1791,
 1792,
 1793,
 1794,
 1795,
 1796,
 1797,
 1798,
 1799,
 1800,
 1801,
 1802,
 1803,
 1804,
 1805,
 1806,
 1807,
 1808,
 1827,
 1828,
 1829,
 1830,
 1831,
 1832,
 1833,
 1834,
 1835,
 1836,
 1837,
 1838,
 1839,
 1840,
 1841,
 1842,
 1843,
 1844,
 1845,
 1846,
 1847,
 1848,
 1849,
 1897,
 1908,
 1920,
 1921,
 1923,
 1924,
 1925,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1967,
 1968,
 1970,
 1971,
 2105,
 2106,
 2107,
 2108,
 2109,
 2110,
 2111,
 2112,
 2113,
 2114,
 2115,
 2116,
 2117,
 2118,
 2151,
 2162,
 2163,
 2190,
 2222,
 2223,
 2235,
 2236,
 2237,
 2238,
 2239,
 2240,
 2241,
 2256,
 2258,
 2259,
 2260,
 2261,
 2291,
 2292,
 2365,
 2371,
 2417,
 2467,
 2468,
 2469,
 2618,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2625,
 2626,
 2627,
 2628,
 2629,
 2630,
 2631,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2664,
 2764,
 2867,
 2868,
 2869,
 2870,
 2871,
 2872,
 3002,
 3057,
 3058,
 3078,
 3079,
 3080,
 3094,
 3104,
 3105,
 3109,
 3110,
 3111,
 3112,
 3142,
 3144,
 3146,
 3215,
 3216,
 3217,
 3218,
 3219,
 3220,
 3221,
 3222,
 3223,
 3224,
 3225,
 3226,
 3227,
 3228,
 3229,
 3230,
 3231,
 3232,
 3233,
 3418,
 3427,
 3441,
 3445,
 3449,
 3450,
 3451,
 3452,
 3453,
 3454,
 3455,
 3498,
 3499,
 3500,
 3501,
 3502,
 3503,
 3504,
 3505,
 3506,
 3507,
 3508,
 3509,
 3510,
 3511,
 3512,
 3513,
 3514,
 3537,
 3538,
 3539,
 3540,
 3541,
 3542,
 3543,
 3544,
 3545,
 3546,
 3547,
 3548,
 3549,
 3550,
 3582,
 3604,
 3627,
 3628,
 3629,
 3640,
 3668,
 3749,
 3769,
 3770,
 3771,
 3772,
 3778,
 3779,
 3780,
 3781,
 3782,
 3783,
 3784,
 3785,
 3786,
 3787,
 3788,
 3789,
 3817,
 3818,
 3819,
 3820,
 3821,
 3822,
 3823,
 3824,
 3825,
 3826,
 3841,
 3842,
 3849,
 3855,
 3856,
 3857,
 3858,
 3865,
 3912,
 3913,
 3914,
 3915,
 3950,
 3951,
 3952,
 3953,
 3954,
 3955,
 3956,
 3957,
 3958,
 3959,
 3960,
 3961,
 3962,
 3963,
 3964,
 3965,
 4003,
 4254,
 4369,
 4370,
 4464,
 4563,
 4564,
 4565,
 4566,
 4569,
 4571,
 4590,
 4606,
 4607,
 4608,
 4609,
 4610,
 4611,
 4612,
 4613,
 4614,
 4615,
 4616,
 4617,
 4630,
 4635,
 4658,
 4706,
 4707,
 4708,
 4709,
 4710,
 4711,
 4712,
 4713,
 4714,
 4716,
 4717,
 4718,
 4719,
 4723,
 4724,
 4805,
 4814,
 4906,
 4908,
 4928,
 4929,
 4930,
 4934,
 4972,
 4973,
 4974,
 4975,
 4979,
 4980,
 4982,
 5018,
 5019,
 5020,
 5021,
 5022,
 5023,
 5024,
 5025,
 5026,
 5040,
 5065,
 5066,
 5116,
 5117,
 5118,
 5174,
 5182,
 5183,
 5184,
 5185,
 5186,
 5197,
 5281,
 5282,
 5285,
 5286,
 5318,
 5319,
 5355,
 5356,
 5358,
 5359,
 5365,
 5378,
 5379,
 5391,
 5416,
 5417,
 5445,
 5461,
 5462,
 5463,
 5464,
 5506,
 5630,
 5631,
 5632,
 5633,
 5634,
 5635,
 5637,
 5639,
 5640,
 5644,
 5664,
 5705,
 5706,
 5746,
 5957,
 6001,
 6012,
 6013,
 6020,
 6025,
 6032,
 6037,
 6052,
 6057,
 6058,
 6059,
 6060,
 6083,
 6131,
 6133,
 6134,
 6135,
 6136,
 6137,
 6138,
 6139,
 6140,
 6146,
 6147,
 6148,
 6149,
 6150,
 6163,
 6171,
 6209,
 6248,
 6249,
 6250,
 6270,
 6316,
 6317,
 6319,
 6320,
 6321,
 6322,
 6323,
 6324,
 6325,
 6326,
 6353,
 6365,
 6366,
 6381,
 6382,
 6391,
 6392,
 6393,
 6394,
 6395,
 6396,
 6397,
 6398,
 6399,
 6400,
 6401,
 6402,
 6403,
 6404,
 6405,
 6406,
 6407,
 6479,
 6480,
 6481,
 6482,
 6483,
 6484,
 6485,
 6486,
 6487,
 6488,
 6489,
 6490,
 6491,
 6492,
 6493,
 6494,
 6495,
 6496,
 6497,
 6498,
 6499,
 6558,
 6559,
 6560,
 6561,
 6562,
 6565,
 6566,
 6567,
 6568,
 6569,
 6570,
 6571,
 6572,
 6574,
 6575,
 6577,
 6578,
 6579,
 6612,
 6613,
 6658,
 6659,
 6660,
 6661,
 6662,
 6666,
 6693,
 6694,
 6765,
 6777,
 6787,
 6788,
 6789,
 6790,
 6791,
 6799,
 6800,
 6801,
 6802,
 6803,
 6804,
 6805,
 6835,
 6836,
 6844,
 6861,
 6862,
 6863,
 6864,
 6865,
 6866,
 6867,
 6868,
 6869,
 6871,
 6872,
 6873,
 6874,
 6875,
 6876,
 6877,
 6878,
 6880,
 6924,
 6925,
 6926,
 6954,
 6960,
 6961,
 6962,
 6963,
 6964,
 6965,
 6966,
 6967,
 6968,
 6969,
 6970,
 6971,
 6972,
 6973,
 6974,
 6975,
 6976,
 6977,
 6978,
 6979,
 6980,
 7058,
 7229,
 7336,
 7341,
 7342,
 7524,
 7530,
 7611,
 7619,
 7620,
 7621,
 7622,
 7623,
 7626,
 7667,
 7668,
 7669,
 7672,
 7680,
 7720,
 7787,
 7788,
 7831,
 7832,
 7833,
 7834,
 7835,
 7836,
 7837,
 7838,
 7839,
 7840,
 7841,
 7842,
 7843,
 7844,
 7845,
 7846,
 7991,
 7992,
 7993,
 7994,
 7995,
 7996,
 7997,
 7998,
 7999,
 8001,
 8002,
 8003,
 8004,
 8005,
 8006,
 8009,
 8028,
 8029,
 8030,
 8031,
 8032,
 8033,
 8034,
 8035,
 8036,
 8037,
 8038,
 8039,
 8040,
 8050,
 8051,
 8052,
 8053,
 8056,
 8057,
 8064,
 8105,
 8131,
 8150,
 8192,
 8193,
 8213,
 8231,
 8232,
 8238,
 8240,
 8248,
 8322,
 8323,
 8324,
 8325,
 8326,
 8327,
 8328,
 8329,
 8330,
 8331,
 8332,
 8333,
 8334,
 8335,
 8336,
 8337,
 8338,
 8339,
 8340,
 8341,
 8347,
 8372,
 8376,
 8398,
 8400,
 8403,
 8437,
 8438,
 8465,
 8477,
 8478,
 8479,
 8480,
 8481,
 8482,
 8483,
 8484,
 8485,
 8486,
 8487,
 8488,
 8489,
 8490,
 8491,
 8492,
 8501,
 8508,
 8513,
 8514,
 8572,
 8676,
 8680,
 8720,
 8721,
 8722,
 8723,
 8724,
 8725,
 8726,
 8727,
 8728,
 8729,
 8730,
 8786,
 8788,
 8790,
 9058,
 9059,
 9060,
 9091,
 9092,
 9093,
 9094,
 9098,
 9160,
 9161,
 9192,
 9251,
 9252,
 9253,
 9254,
 9255,
 9256,
 9257,
 9261,
 9269,
 9270,
 9277,
 9322,
 9331,
 9332,
 9402,
 9415,
 9416,
 9417,
 9418,
 9419,
 9420,
 9421,
 9422,
 9423,
 9424,
 9425,
 9426,
 9427,
 9428,
 9429,
 9430,
 9431,
 9432,
 9433,
 9434,
 9436,
 9437,
 9447,
 9448,
 9449,
 9450,
 9451,
 9482,
 9483,
 9484,
 9485,
 9486,
 9488,
 9489,
 9501,
 9502,
 9503,
 9504,
 9505,
 9506,
 ...]

In [35]:
ec_plants_sm = ec_plants.iloc[ids_sm, :]

In [36]:
ec_plants_sm.to_csv("swiss_prot_ec_plants_sm.csv", index=False)

In [1]:
import json

with open("maps_secondary_metabolism_ec_numbers.json", "r") as f:
    maps_enzymes = json.load(f)

sm_ec_numbers = []

for ec in maps_enzymes.values():
    sm_ec_numbers.extend(ec)

In [2]:
import pandas as pd
ec_plants = pd.read_csv("swiss_prot_ec_plants.csv")
ids_sm = []
for i, ec_numbers in enumerate(ec_plants.EC):
    ec = ec_numbers.split(";")
    for ec_ in ec:
        if ec_ in sm_ec_numbers:
            ids_sm.append(i)
            break

In [5]:
ec_plants_sm = ec_plants.iloc[ids_sm, :]
ec_plants_sm.head()

,accession,name,sequence,EC,lineage,species,taxonomy_id,1,2,3,...,7.4.2.5,7.4.2.8,7.5.2.11,7.6.2.1,7.6.2.11,7.6.2.13,7.6.2.2,7.6.2.3,7.6.2.5,7.6.2.8
11,Q9MBC1,3AT_PERFR,VIETCRVGPPPDSVAEQSVPLTFFDMTWLHFHPMLQLLFYEFPCSK...,2.3.1.215,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Perilla frutescens,48386,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26,Q41247,AL7A1_BRANA,MGSASKEYEFLSEIGLSSSHNLGNYVGGKWLGNGPLVSTLNPANNQ...,1.2.1.3,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Brassica napus,3708,1,0,0,...,0,0,0,0,0,0,0,0,0,0
30,P49252,AMO_LENCU,KFALFSVLTLLSFHAVFSFTPLHTQHPLDPITKEEFLAVQTIVQNK...,1.4.3.21,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Lens culinaris,3864,1,0,0,...,0,0,0,0,0,0,0,0,0,0
40,A2XNK3,ASA1_ORYSI,MASLVLSLRIAPSTPPLGLGGGRFRGRRGAVACRAATFQQLDAVAV...,4.1.3.27,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Oryza sativa subsp. indica,39946,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,A0A0S2IHL6,BASM1_KALSE,MWKLKIAEGDKNDPYLYSTNNFVGRQTWEFDPDYVGSPGELEEVEE...,5.4.99.39,Eukaryota;Viridiplantae;Streptophyta;Embryophy...,Kalopanax septemlobus,228393,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
import json

# save json file
with open("maps_secondary_metabolism_ec_numbers.json", "w") as f:
    json.dump(maps_enzymes, f)

In [37]:
ec_plants = pd.read_csv("./data/trembl_prot_ec_plants.csv")
ids_sm = []
for i, ec_numbers in enumerate(ec_plants.EC):
    ec = ec_numbers.split(";")
    for ec_ in ec:
        if ec_ in sm_ec_numbers:
            ids_sm.append(i)
            break

In [38]:
ec_plants_sm = ec_plants.iloc[ids_sm, :]

In [39]:
ec_plants_sm.shape

(47600, 7)

In [40]:
ec_plants_sm.to_csv("./trembl_prot_ec_plants_sm.csv", index=False)