In [2]:
import pandas as pd

dataset = pd.read_csv("swiss_prot_enzymes_filtered.csv")

dataset

,accession,name,sequence,enzyme
0,P0C9F0,1001R_ASFK5,MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLE...,0
1,P0C9F1,1001R_ASFM2,MVRLFHNPIKCLFYRGSRKTREKKLRKSLKKLNFYHPPGDCCQIYR...,0
2,P0C9F2,1001R_ASFP4,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,0
3,Q65209,1002L_ASFB7,MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKKLK...,0
4,P0C9F4,1002L_ASFK5,MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKNLE...,0
...,...,...,...,...
362676,Q9NX65,ZSC32_HUMAN,MMAAVKSTEAHPSSNKDPTQGQKSALQGNSPDSEASRQRFRQFCYQ...,0
362677,Q80VJ6,ZSC4C_MOUSE,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...,0
362678,O15535,ZSC9_HUMAN,MNTNSKEVLSLGVQVPEAWEELLTMKVEAKSHLQWQESRLKRSNPL...,0
362679,Q8NBB4,ZSCA1_HUMAN,MLPRPKAPASPRRPQTPTPSEQDADPGPASPRDTEAQRLRFRQFQY...,0
362680,Q7Z7L9,ZSCA2_HUMAN,MMAADIPRVTTPLSSLVQVPQEEDRQEEEVTTMILEDDSWVQEAVL...,0

In [3]:
# Export as FASTA file
with open('swiss_prot_enzymes_filtered.fasta', 'w') as f:
    for idx, row in dataset.iterrows():
        f.write(f">{row['accession']}\n{row['sequence']}\n")

In [5]:
# shuffle the dataset
dataset = dataset.sample(frac=1).reset_index(drop=True)
dataset

,accession,name,sequence,enzyme
0,P08153,SWI5_YEAST,MDTSNSWFDASKVQSLNFDLQTNSYYSNARGSDPSSYAIEGEYKTL...,0
1,Q9KCR5,PROA_HALH5,MSELIEKAKQAQQASKQLAILTTEEKNRALKQIADQLLVERTYLIE...,1
2,Q8M9V5,RK36_CHAGL,MKVQASVRKICENCRLIRRRRRVMVVCKNPKHKQRQG,0
3,Q8AY78,VSP5M_TRIST,MVLIRVLANLLILQLSYAQKSSELVVGGRPCNINEHRSLVVLFNSS...,1
4,O05947,SYT_RICPR,MINISFPDGSVKQFAQNITAFEIVNAISMSLAKAAIVVEINGELKD...,1
...,...,...,...,...
358361,O67527,ATPD_AQUAE,MLKRKELARKAVRLIVKKVPKEKESILKVDEFLGTLSTAYRKDKLL...,0
358362,Q0AFT2,MURA_NITEC,MQKLVIHGGSKLHGEISISGAKNAALPVLCASLLTAEPFAIQNIPH...,1
358363,Q9USN5,GDH2_SCHPO,MYLTKQIPHYSRIHTTQLLTVVNHRTIPFKIRGSFSNCRRYSNFAT...,1
358364,Q9CNV9,Y314_PASMU,MKIFAVLSAFLMPFVVPNTTVNGYKDLRFGMTIEQAKETKLCEDQW...,0
358365,O59931,RL13_CANAL,MAISKNLPLLNNHFRKHWQERVRVHFDQAGKKASRRQSRLRKAAKI...,0

In [11]:
# split the data with sklearn 
from sklearn.model_selection import train_test_split

train, test = train_test_split(dataset, test_size=0.05)
print(test.shape)
train, validation = train_test_split(train, test_size=0.05)
print(train.shape)
print(validation.shape)
train.to_csv("./data/train.csv", index=False)
validation.to_csv("./data/validation.csv", index=False)
test.to_csv("./data/test.csv", index=False)

(17919, 4)
(323424, 4)
(17023, 4)

In [14]:
# count the number of classes
print(train["enzyme"].value_counts())
print(validation["enzyme"].value_counts())
print(test["enzyme"].value_counts())

0    172903
1    150521
Name: enzyme, dtype: int64
0    9012
1    8011
Name: enzyme, dtype: int64
0    9509
1    8410
Name: enzyme, dtype: int64